---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by zhangxin.
--- DateTime: 2022/9/19 09:21
---

local cjson = require("cjson")
local log_file = io.open("resty.log", "w")
io.output(log_file)

local _M = {}

local LEVEL = {
    TRACE = {
        val = -2,
        name = "trace"
    },
    DEBUG = {
        val = -1,
        name = "debug"
    },
    INFO = {
        val = 0,
        name = "info"
    },
    WARN = {
        val = 1,
        name = "warn"
    },
    ERROR = {
        val = 2,
        name = "error"
    },
}

local allowed_level = LEVEL.WARN

local seq_no = 0

function log(level, msg)
    if level.val >= allowed_level.val then
        seq_no = seq_no + 1
        local log_entry = {
            level = level.name,
            content = msg,
            log_seq_no = seq_no
        }
        local log_line = cjson.encode(log_entry)
        io.write(log_line, "\n")
    end
end

ngx.timer.every(30, function()
    io.flush()
end)

_M.LEVEL = LEVEL
_M.log = log
return _M
